 - name: Deploy to Firebase Hosting
 uses: FirebaseExtended/action-hosting-deploy@v0.6-alpha

 // Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyAAookmINMnhy-GvBQ0CxKzcYxHoGic6ko",
  authDomain: "planinc-1719027737497.firebaseapp.com",
  projectId: "planinc-1719027737497",
  storageBucket: "planinc-1719027737497.appspot.com",
  messagingSenderId: "1030194866424",
  appId: "1:1030194866424:web:d5a75d8c0838d01943730d",
  measurementId: "G-35QV0P4LYY"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const analytics = getAnalytics(app);
